# Settings documented at https://docs.astral.sh/ruff/settings/.
# Rules documented at https://docs.astral.sh/ruff/rules/.

[lint]
# Ruff default value: ["E4", "E7", "E9", "F"].
select = [
    "E4",  # pycodestyle errors 4xx
    "E7",  # pycodestyle errors 7xx
    "E9",  # pycodestyle errors 9xx
    "F"    # Pyflakes
]
ignore = []
